arm_home_config:
  panda_joint1: 0
  panda_joint2: 0
  panda_joint3: 0
  panda_joint4: -1.5707963267948966
  panda_joint5: 0
  panda_joint6: 1.5707963267948966
  panda_joint7: 0.7853981633974483
arm_joint_names:
- panda_joint1
- panda_joint2
- panda_joint3
- panda_joint4
- panda_joint5
- panda_joint6
- panda_joint7
arm_link_names:
- panda_link1
- panda_link2
- panda_link3
- panda_link4
- panda_link5
- panda_link6
- panda_link7
joint_max_forces:
- 5000.0
- 3000.0
- 2000.0
- 1500.0
- 1000.0
- 1000.0
- 1000.0
base_position:
- -0.42
- 0.0
- 0.04
base_rpy:
- 0
- 0
- 0
fixed_base: 1
gripper_home_config:
  panda_finger_joint1: 0
  panda_finger_joint2: 0
gripper_joint_names:
- panda_finger_joint1
- panda_finger_joint2
gripper_link_names:
- panda_leftfinger
- panda_rightfinger
tool_frame_name: tool
