group_name: "panda_arm"
max_try: 3
up_distance: 0.15
exit_distance: 0.1
entrance_distance: -0.06
up1: 0.1
up2: 0.1
max_attempts: 5
plan_step_length: 0.02
via_pose1_px: 0.25
via_pose1_py: 0
via_pose1_pz: 0.4
via_pose2_px: 0.25
via_pose2_py: 0.3
via_pose2_pz: 0.4
via_pose3_px: 0.25
via_pose3_py: -0.3
via_pose3_pz: 0.4
via_pose_ox: 0
via_pose_oy: 1
via_pose_oz: 0
via_pose_ow: 0
home_joint1: 0
home_joint2: 0
home_joint3: 0
home_joint4: -90
home_joint5: 0
home_joint6: 90
home_joint7: 0
